WebsiteBanHang/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;
using PagedList;
using PagedList.Mvc;


namespace WebsiteBanHang.Controllers
{
    public class TrangChuController : Controller
    {
        DBWebsiteQuanLyCuaHangSoi data = new DBWebsiteQuanLyCuaHangSoi();
        // GET: TrangChu

        private List<SanPham> LaySanPhamMoi(int count)
        {
            return data.SanPhams.OrderByDescending(a => a.ngaycapnhat).Take(count).ToList();
        }

        public ActionResult TrangChuCuaHang()
        {
            var sanpham = LaySanPhamMoi(3);
            return View(sanpham);
        }
        public ActionResult SanPhamMoi()
        {
            var sanphammoi = LaySanPhamMoi(5);
            return PartialView(sanphammoi);
        }
        public ActionResult LoaiSanPham()
        {
            var loaisanpham = from lsp in data.LoaiSanPhams select lsp;
                return PartialView(loaisanpham);
        }
        
        public ActionResult SPTheoLoai(int id)
        {
            var sptheoloai = from s in data.SanPhams where s.maloaisanpham == id select s;
            return View(sptheoloai);
        }
        public ActionResult TrangSanPham(int ? page)
        {
            // tao bien quy dinh so san pham tren moi trang
            int pageSize = 6;
            // tao bien so trang
            int pageNum = (page ?? 1);

            //lay san pham theo abum ban chay

            var sanpham = LaySanPhamMoi(15);
            return View(sanpham.ToPagedList(pageNum, pageSize));
        }

        //public ActionResult TrangSanPham(int id)
        //{
        //    var sanpham1 = from s in data.SanPhams where s.maloaisanpham == id select s;
        //    return View(sanpham1);
        //}

        public ActionResult TrangChiTietSanPham(int id)
        {
            var sanpham = from s in data.SanPhams where s.masp == id select s;

            return View(sanpham.Single());
        }

        public ActionResult TrangChuTest()
        {
            return View();
        }

        public ActionResult Search(String TimKiem = "")
        {
            var list = data.SanPhams.Where(x => x.tensanpham.Contains(TimKiem)).ToList();
            return View(list);
        }

        //Get
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy([Bind(Include = "makh,tenkh,diachi,email,sdt,username,password")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                data.KhachHangs.Add(khachHang);
                data.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khachHang);
        }
    }
}

WebsiteBanHang/Areas/NV/Views/Shared/Trangpageconnv.cshtml
<!DOCTYPE html>
<link href="~/TatCaThuocTinhTrangChu/css/style3.css" rel="stylesheet" />
<link href="~/TatCaThuocTinhTrangChu/css/style2.css" rel="stylesheet" />
<link href="~/TatCaThuocTinhTrangChu/css/style1.css" rel="stylesheet" />
<link href="~/TatCaThuocTinhTrangChu/css/style.css" rel="stylesheet" />
<link href="~/TatCaThuocTinhTrangChu/css/responsiveslides.css" rel="stylesheet" />
<link href="~/TatCaThuocTinhTrangChu/css/flexslider.css" rel="stylesheet" />
<link href="~/TatCaThuocTinhTrangChu/css/style4.css" rel="stylesheet" />

<html>

<head>
    <title>Mobilestore Website Template | single :: W3layouts</title>
    <link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
    <meta name="keywords" content="Mobilestore iphone web template, Android web template, Smartphone web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <link href='//fonts.googleapis.com/css?family=Londrina+Solid|Coda+Caption:800|Open+Sans' rel='stylesheet' type='text/css'>
    <script src="~/TatCaThuocTinhTrangChu/js/jquery.min.js"></script>
    <script src="~/TatCaThuocTinhTrangChu/js/jqzoom.pack.1.0.1.js" type="text/javascript"></script>
    <link rel="stylesheet" href="css/flexslider.css" type="text/css" media="screen" />
    <script src="~/TatCaThuocTinhTrangChu/js/imagezoom.js"></script>
    <!-- FlexSlider -->
    <script defer src="js/jquery.flexslider.js"></script>
    <script>
        // Can also be used with $(document).ready()
        $(window).load(function () {
            $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
            });
        });</script>
    <!----->
    <script>
        $(document).ready(function () {
            $(".menu_body").hide();
            //toggle the componenet with class menu_body
            $(".menu_head").click(function () {
                $(this).next(".menu_body").slideToggle(600);
                var plusmin;
                plusmin = $(this).children(".plusminus").text();

                if (plusmin == '+')
                    $(this).children(".plusminus").text('-');
                else
                    $(this).children(".plusminus").text('+');
            });
        });</script>
</head>
<style type="text/css">
    #blockdatmua div {
        border-top: 1px solid #0879c9;
        display: block;
    }

    #Datmua a {
        clear: both;
        background-color: red;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }

        #Datmua a:hover {
            background-color: gray;
            color: red;
        }

    .MenuTrang li {
        display: inline;
    }
</style>
<body>
    <div class="wrap">
        <!----start-Header---->
        <div class="header">
            <div class="search-bar">
                <form>
                    <input type="text"><input type="submit" value="Tìm kiếm" />
                </form>
            </div>
            <div class="clear"> </div>
            <div class="header-top-nav">
                <ul>
                    @if (Session["aUser"] != null)
                    {
                        
                        <li><a href="@Url.Action("IndexRoleUser","NV/NhanViens",new { area =""})">@Session["aUser"].ToString()</a></li>
                        <li><a href="@Url.Action("logout","DangNhap/Account", new {area ="" })">Đăng Xuất</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("DangKy","DangNhap/Account", new {area ="" })">Đăng ký</a></li>
                        <li><a href="@Url.Action("DangNhap","DangNhap/Account", new {area ="" })">Đăng nhập</a></li>
                    }
                    <li><a href="#">Hỗ trợ</a></li>
                    <li><a href="@Url.Action("GioHang","GioHang", new {area ="" })">Giỏ hàng</a></li>
                    <li><a href="#"><span>Thanh toán&nbsp;&nbsp; </span></a></li>
                    <li>
                        @Html.Action("GioHangPartial", "GioHang", new { area = "" })
                    </li>
                </ul>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <div class="clear"> </div>
    <div class="top-header">
        <div class="wrap">
            <!----start-logo---->
            <div class="logo">
                <a href="index.html"><img src="~/TatCaThuocTinhTrangChu/images/HB.png" title="logo" /></a>
            </div>
            <!----end-logo---->
            <!----start-top-nav---->
            <div class="top-nav">
                <ul>
                    <li><a href="@Url.Action("TrangChuCuaHang","TrangChu", new {area ="" })">Trang Chủ</a></li>
                    <li><a href="@Url.Action("TrangSanPham","TrangChu", new {area ="" })">Danh mục sản phẩm</a></li>
                    <li><a href="store.html">Thanh toán</a></li>
                    <li><a href="store.html">Chính sách giao hàng</a></li>
                    <li><a href="blog.html">Liên hệ</a></li>
                    <li><a href="contact.html">Thư viện</a></li>
                </ul>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <!----End-top-nav---->
    <!----End-Header---->
    <div class="clear"> </div>
    <div class="wrap">
        <div class="content">
            <div class="content-grids">
                <div align="left" style="min-height:800px;">


                    <div id="wrap" align="center">

                        <a id="show_cart" href="javascript:void(0)">View My Cart</a>

                        <ul>
                            @RenderBody()

                        </ul>
                        <br clear="all" />
                    </div>

                </div>
            </div>
        </div>

    </div>
    <div class="content-sidebar">
        <h4>Thêm - Xóa - Sửa</h4>
        <ul>
            <li><a href="@Url.Action("IndexRoleUser","NV/NhanViens",new {area=""})">Thông tin cá nhân</a></li>
            <li><a href="@Url.Action("Index","NV/SanPhams",new {area=""})">Sản phẩm</a></li>
            <li><a href="@Url.Action("Index","NV/LoaiSanPhams",new {area=""})">Loại sản phẩm</a></li>
            <li><a href="@Url.Action("Index","NV/QuocQias",new {area=""})">Quốc gia</a></li>
            <li><a href="@Url.Action("Index","NV/KhachHangs",new {area=""})">Khách hàng</a></li>
            <li><a href="@Url.Action("Index","NV/DonHangs",new {area=""})">Đơn hàng</a></li>
            <li><a href="@Url.Action("Index","NV/LoaiSanPhams",new {area=""})">Phiếu nhập hàng</a></li>
            
        </ul>
    </div>
    </div>
    <div class="clear"> </div>
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h3>Our Info</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h3>Latest-News</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h3>Store Location</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <h3>Order-online</h3>
                    <p>080-1234-56789</p>
                    <p>080-1234-56780</p>
                </div>
                <div class="col_1_of_4 span_1_of_4 footer-lastgrid">
                    <h3>News-Letter</h3>
                    <form>
                        <input type="text"><input type="submit" value="go" />
                    </form>
                    <h3>Follow Us:</h3>
                    <ul>
                        <li><a href="#"><img src="images/twitter.png" title="twitter" />Twitter</a></li>
                        <li><a href="#"><img src="images/facebook.png" title="Facebook" />Facebook</a></li>
                        <li><a href="#"><img src="images/rss.png" title="Rss" />Rss</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clear"> </div>
        <div class="wrap">
            <div class="copy-right">
                <p>&copy; 2013 Mobile Store. All Rights Reserved | Design by  <a href="http://w3layouts.com/">W3Layouts</a></p>
            </div>
        </div>
    </div>
</body>
</html>